---
version: 2.1
jobs:
  shellcheck_and_store:
    docker:
      - image: circleci/buildpack-deps:disco
    shell: /bin/bash
    working_directory: /home/circleci/packages
    steps:
      - checkout
      - run:
          name: Install shellcheck and shfmt v3
          command: |
            set +e && set +o pipefail
            sudo apt update && sudo apt full-upgrade -y && sudo apt install -y add-apt-key apt-utils isoquery lsb software-properties-common
            sudo apt-add-repository -ysu ppa:roguescholar/ppa
            sudo apt install -y bash git golang-1.12 shellcheck
            mkdir -p /home/circleci/go && export GOPATH="/home/circleci/go" && export GOROOT="/usr/lib/go-1.12" && export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
            cd $(mktemp -d) && go mod init tmp && go get mvdan.cc/sh/v3/cmd/shfmt
      - run:
          name: Test shell scripts and record file stats
          command: |
            set +e && set +o pipefail
            mkdir ~/test-reports
            echo "Calculating script file stats..."
            find . -type f -name '*.sh' | xargs wc -lmw 2>&1 | tee /home/circleci/test-reports/script-file-stats.txt
            echo "Running shell script tests..."
            find . -type f -name '*.sh' | xargs shellcheck -ax -s bash 2>&1 | tee -a /home/circleci/test-reports/shellcheck-output.txt
            find . -type f -name '*.sh' | xargs shfmt -p -d -i 2 -ci -s 2>&1 | tee -a /home/circleci/test-reports/shfmt3-output.txt
      - store_artifacts:
          path: /home/circleci/test-reports
          destination: script-tests
  build_libs_and_save:
    docker:
      - image: circleci/buildpack-deps:disco
    shell: /bin/bash
    working_directory: /home/circleci/packages
    steps:
      - checkout
      - run:
          name: Update apt and install build dependencies
          command: |
            sudo apt update && sudo apt full-upgrade -y && sudo apt install -y adequate apt-utils autopkgtest bash binutils-multiarch build-essential \
            debhelper debtags devscripts dh-acc dh-make dselect groff libgconf2-dev libglade2-dev libglib-perl libgtk2-perl libvte-dev libgtk2-perl \
            libextutils-pkgconfig-perl libextutils-depends-perl libunique-dev lsb perl software-properties-common quilt xauth xfonts-base xvfb
      - run:
          name: Build libgnome2-gconf-perl
          command: cd /home/circleci/packages/libgnome2-gconf-perl && ./make_debian.sh
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl_1.044-6_amd64.deb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl-dbgsym_1.044-6_amd64.ddeb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl_1.044-6.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl_1.044-6_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl_1.044-6_amd64.buildinfo
      - run:
          name: Build libgnome2-vte-perl
          command: cd /home/circleci/packages/libgnome2-vte-perl && ./make_debian.sh
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl_0.11-2_amd64.deb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl-dbgsym_0.11-2_amd64.ddeb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl_0.11-2.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl_0.11-2_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl_0.11-2_amd64.buildinfo
      - run:
          name: Build libgtk2-ex-simple-list-perl
          command: cd /home/circleci/packages/libgtk2-ex-simple-list-perl && ./make_debian.sh
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp/libgtk2-ex-simple-list-perl_0.50-3_all.deb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp/libgtk2-ex-simple-list-perl_0.50-3.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp/libgtk2-ex-simple-list-perl_0.50-3_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp/libgtk2-ex-simple-list-perl_0.50-3_amd64.buildinfo
      - run:
          name: Build libgtk2-gladexml-perl
          command: cd /home/circleci/packages/libgtk2-gladexml-perl && ./make_debian.sh
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl_1.007-2_amd64.deb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl-dbgsym_1.007-2_amd64.ddeb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl_1.007-2.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl_1.007-2_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl_1.007-2_source.buildinfo
      - run:
          name: Build libgtk2-unique-perl
          command: cd /home/circleci/packages/libgtk2-unique-perl && ./make_debian.sh
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl_0.05-3_amd64.deb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl-dbgsym_0.05-3_amd64.ddeb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl_0.05-3.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl_0.05-3_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl_0.05-3_source.buildinfo
      - save_cache:
          key: lib-package-cache
          paths:
            - /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl_1.044-6_amd64.deb
            - /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl_0.11-2_amd64.deb
            - /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp/libgtk2-ex-simple-list-perl_0.50-3_amd64.deb
            - /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl_1.007-2_amd64.deb
            - /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl_0.05-3_amd64.deb
workflows:
  version: 2
  build:
    jobs:
      - shellcheck_and_store
      - build_libs_and_save
