---
version: 2.1
executors:
  ubuntu-disco:
    docker:
      - image: circleci/buildpack-deps:disco
    shell: /bin/bash
    working_directory: /home/circleci/packages
    environment:
      DEBUILD_DPKG_BUILDPACKAGE_OPTS: "-D -F -sa"
      DEBUILD_LINTIAN_OPTS: "-E -I -i --pedantic"
jobs:
  scripts_test_and_store:
    executor: ubuntu-disco
    environment:
      GOPATH: "/home/circleci/go"
      GOROOT: "/usr/lib/go-1.11"
      GOBIN: "/home/circleci/go/bin"
    steps:
      - checkout
      - run:
          name: Install go and shellcheck
          command: |
            sudo apt update
            sudo apt full-upgrade -y
            sudo apt install -y add-apt-key apt-transport-https apt-utils golang-1.11 golang-1.11-race-detector-runtime shellcheck \
            software-properties-common
      - run:
          name: Install shfmt v3
          command: |
            export PATH="$PATH:$GOROOT/bin:$GOBIN"
            mkdir -p $GOBIN
            sudo go get mvdan.cc/sh/v3/cmd/shfmt
            sudo go install mvdan.cc/sh/v3/cmd/shfmt
            cd $(mktemp -d); go mod init tmp; go get mvdan.cc/sh/v3/cmd/shfmt
            go build mvdan.cc/sh/v3/cmd/shfmt
            sudo cp ./shfmt /usr/local/bin
      - run:
          name: Test shell scripts and record file stats
          command: |
            set +e
            set +o pipefail
            mkdir -p /home/circleci/script-test-reports
            echo "Calculating script file stats..."
            find . -type f -name '*.sh' | xargs wc -lmw 2>&1 | tee -a /home/circleci/script-test-reports/script-file-stats.txt
            echo "Running shellcheck tests..."
            find . -type f -name '*.sh' | xargs shellcheck -ax -s bash 2>&1 | tee -a /home/circleci/script-test-reports/shellcheck-output.txt
            echo "Running shfmt tests..."
            find . -type f -name '*.sh' | xargs shfmt -d -ci -s -i 2 2>&1 | tee -a /home/circleci/script-test-reports/shfmt3-output.txt
      - store_artifacts:
          path: /home/circleci/script-test-reports
          destination: script-tests
  build_libs_and_save:
    executor: ubuntu-disco
    steps:
      - checkout
      - run:
          name: Update apt and install build dependencies
          command: >
            sudo apt update && sudo apt full-upgrade -y && sudo apt install -y adequate apt-transport-https apt-utils autopkgtest bash
            binutils-multiarch build-essential curl debhelper debtags devscripts dh-acc dh-make dselect gnupg groff libgconf2-dev libglade2-dev
            libglib-perl libgtk2-perl libvte-dev libgtk2-perl libextutils-pkgconfig-perl libextutils-depends-perl libunique-dev perl
            software-properties-common quilt wget xauth xfonts-base xvfb
      - run:
          name: Build libgnome2-gconf-perl
          command: cd /home/circleci/packages/libgnome2-gconf-perl && ./make_debian.sh
      - persist_to_workspace:
          root: /home/circleci/packages/libgnome2-gconf-perl/tmp
          paths: libgnome2-gconf-perl_*.deb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl_1.044-7~asbru1_amd64.deb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl-dbgsym_1.044-7~asbru1_amd64.ddeb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl_1.044-7~asbru1.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl_1.044-7~asbru1_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-gconf-perl/tmp/libgnome2-gconf-perl_1.044-7~asbru1_amd64.buildinfo
      - run:
          name: Build libgnome2-vte-perl
          command: cd /home/circleci/packages/libgnome2-vte-perl && ./make_debian.sh
      - persist_to_workspace:
          root: /home/circleci/packages/libgnome2-vte-perl/tmp
          paths: libgnome2-vte-perl_*.deb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl_0.11-2_amd64.deb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl-dbgsym_0.11-2_amd64.ddeb
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl_0.11-2.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl_0.11-2_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgnome2-vte-perl/tmp/libgnome2-vte-perl_0.11-2_amd64.buildinfo
      - run:
          name: Build libgtk2-ex-simple-list-perl
          command: cd /home/circleci/packages/libgtk2-ex-simple-list-perl && ./make_debian.sh
      - persist_to_workspace:
          root: /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp
          paths: libgtk2-ex-simple-list-perl_*.deb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp/libgtk2-ex-simple-list-perl_0.50-3_all.deb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp/libgtk2-ex-simple-list-perl_0.50-3.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp/libgtk2-ex-simple-list-perl_0.50-3_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-ex-simple-list-perl/tmp/libgtk2-ex-simple-list-perl_0.50-3_amd64.buildinfo
      - run:
          name: Build libgtk2-gladexml-perl
          command: cd /home/circleci/packages/libgtk2-gladexml-perl && ./make_debian.sh
      - persist_to_workspace:
          root: /home/circleci/packages/libgtk2-gladexml-perl/tmp
          paths: libgtk2-gladexml-perl_*.deb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl_1.007-2_amd64.deb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl-dbgsym_1.007-2_amd64.ddeb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl_1.007-2.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl_1.007-2_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-gladexml-perl/tmp/libgtk2-gladexml-perl_1.007-2_amd64.buildinfo
      - run:
          name: Build libgtk2-unique-perl
          command: cd /home/circleci/packages/libgtk2-unique-perl && ./make_debian.sh
      - persist_to_workspace:
          root: /home/circleci/packages/libgtk2-unique-perl/tmp
          paths: libgtk2-unique-perl_*.deb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl_0.05-3_amd64.deb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl-dbgsym_0.05-3_amd64.ddeb
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl_0.05-3.dsc
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl_0.05-3_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/libgtk2-unique-perl/tmp/libgtk2-unique-perl_0.05-3_amd64.buildinfo
  build_asbru_deb_and_save:
    executor: ubuntu-disco
    steps:
      - checkout
      - run:
          name: Update apt and install build dependencies
          command: >
            sudo apt update && sudo apt full-upgrade -y && sudo apt install -y apt-transport-https apt-utils autopkgtest bash binutils-multiarch
            build-essential curl dbus-user-session debhelper devscripts dh-acc dh-make dh-make-perl dpkg ftp gconf-service gconf-service-backend
            gconf2-common gnupg groff gtk2-engines-pixbuf libargon2-1 libcairo-perl libcanberra-gtk-module libcap2 libcrypt-blowfish-perl
            libcrypt-cbc-perl libcrypt-rijndael-perl libcryptsetup12 libdbus-glib-1-2 libdevmapper1.02.1 libexpect-perl libgconf-2-4 libglade2-0
            libglib-perl libgtk2-perl libip4tc0 libjson-c3 libnet-arp-perl libnet-proxy-perl libnss-systemd libossp-uuid-perl libpam-systemd
            libpango-perl libsocket6-perl libunique-1.0-0 libvte9 libxml-parser-perl libyaml-perl openssh-client perl quilt
            software-properties-common systemd systemd-sysv telnet wget
      - attach_workspace:
          at: /home/circleci/packages
      - run:
          name: Install library dependencies
          command: find /home/circleci -type f -name 'lib*.deb' | sudo xargs dpkg -i
      - run:
          name: Build asbru-cm Debian package
          command: cd /home/circleci/packages/asbru-cm && ./make_debian.sh
      - persist_to_workspace:
          root: /home/circleci/packages/asbru-cm/tmp
          paths: asbru-cm_*.deb
      - store_artifacts:
          path: /home/circleci/packages/asbru-cm/tmp/asbru-cm_5.2.0-1~local_amd64.deb
      - store_artifacts:
          path: /home/circleci/packages/asbru-cm/tmp/asbru-cm-dbgsym_5.2.0-1~local_amd64.ddeb
      - store_artifacts:
          path: /home/circleci/packages/asbru-cm/tmp/asbru-cm_5.2.0-1~local.dsc
      - store_artifacts:
          path: /home/circleci/packages/asbru-cm/tmp/asbru-cm_5.2.0-1~local_amd64.changes
      - store_artifacts:
          path: /home/circleci/packages/asbru-cm/tmp/asbru-cm_5.2.0-1~local_amd64.buildinfo
  build_asbru_rpm_and_save:
    docker:
      - image: fedora:30
    shell: /bin/bash
    working_directory: /home/circleci/packages
    steps:
      - run:
          name: Update dnf and install build dependencies
          command: >
            dnf -y upgrade && dnf -y install bash bash-completion coreutils curl diffutils ftp gcc git jq make patch perl pkgconfig python rpm-build
            rpm-devel rpmdevtools rpmlint sudo telnet vte wget
      - checkout
      - run:
          name: Build asbru-cm RPM package
          command: cd /home/circleci/packages/asbru-cm && ./make_rpm.sh
      - store_artifacts:
          path: /home/circleci/packages/asbru-cm/rpm/RPMS/noarch
          destination: rpm-package
  test_deb_packages:
    executor: ubuntu-disco
    steps:
      - run:
          name: Update apt and install testing packages
          command: >
            sudo apt update && sudo apt full-upgrade -y && sudo apt install -y abi-compliance-checker add-apt-key adequate apt-transport-https apt-utils
            autopkgtest curl debhelper debtags dpkg-dev dselect fakeroot gnupg gzip lintian pbuilder piuparts schroot software-properties-common
      - attach_workspace:
          at: deb_packagess
      - run:
          name: Install built packages
          command: |
            cd deb_packages
            find /home/circleci -type f -name '*.deb' | sudo xargs dpkg -i
      - run:
          name: Add packagecloud.io repository for upgrade tests
          command: |
            curl -L https://packagecloud.io/asbru-cm/asbru-cm/gpgkey | sudo apt-key add -
            sudo apt-add-repository -ysu 'deb https://packagecloud.io/asbru-cm/asbru-cm/ubuntu/ disco main'
      - run:
          name: Test package installation results
          command: >
            mkdir -p /home/circleci/deb-test-reports;
            echo "Testing library package install results...";
            piuparts libgnome2-gconf-perl libgnome2-vte-perl libgtk2-ex-simple-list-perl libgtk2-gladexml-perl libgtk2-unique-perl asbru-cm 2>&1
            | tee -a /home/circleci/deb-test-reports/piuparts.txt
      - store_artifacts:
          path: /home/circleci/deb-test-reports
          destination: deb-package-tests
workflows:
  version: 2
  asbru-cm-test-build:
    jobs:
      - scripts_test_and_store:
          filters:
            branches:
              only: master
      - build_libs_and_save:
          filters:
            branches:
              only: master
      - build_asbru_deb_and_save:
          requires:
            - build_libs_and_save
          filters:
            branches:
              only: master
      - build_asbru_rpm_and_save:
          filters:
            branches:
              only: master
      - test_deb_packages:
          requires:
            - build_libs_and_save
            - build_asbru_deb_and_save
          filters:
            branches:
              only: master
