
  name: asbru-cm
  base: core18
  version: '5.2.0'
  summary: Multi-session remote terminal (SSH) connection manager
  description: |
    Ásbrú Connection Manager is an SSH client that allows users to organize
    multiple remote terminal sessions (SSH, Telnet, etc.) using a single client
    application, thanks to a tabbed interface reminiscent of modern web browsers.
    Connections can be grouped to allow launching multiple connections to related
    hosts with a single command, or even multiplexed, with multiple client
    sessions being opened to the same remote host. Every aspect of each
    connection can be managed independently, from environment variables to
    appearance, logging to crontabs.
  grade: devel
  confinement: devmode
  architectures:
  - build-on: amd64
    run-on: all
  icon: res/asbru-logo.svg
  license: GPL-3.0-or-later
  title: Ásbrú Connection Manager
  type: app

  apps:
    asbru-cm:
      command: usr/bin/asbru-cm
      plugs: [
        alsa, dbus, gsettings, home, network, network-bind, network-control,
        password-manager-service, ssh-keys, unity7, x11
      ]

  parts:
    project-files:
    plugin: copy
    files:
      pac/*  : /
      run.sh : usr/bin/run.sh
    after: [integration]

  integration:
  plugin: nil
  stage-packages:
   - libvte9
   - libvte-common
   - libvte-2.91-common
   - libcairo-perl
   - libgtk2-perl
   - libglib-perl
   - libpango-perl
   - libgnome2-gconf-perl
   - libsocket6-perl
   - libexpect-perl
   - libnet-proxy-perl
   - libfindbin-libs-perl
   - libyaml-perl
   - libcrypt-cbc-perl
   - libcrypt-blowfish-perl
   - libgtk2-gladexml-perl
   - libgtk2-ex-simple-list-perl
